--Concepção de inicial de tabelas

CREATE TABLE IMAGE_MOVIE(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IMDB_PRIMARY_IMAGE_URL VARCHAR(1000) NOT NULL,
	WIDTH INT NULL,
	HEIGHT INT NULL
);
GO

CREATE INDEX IMAGE_MOVIE_PRIMARYIMAGEURL_IDX
ON IMAGE_MOVIE(IMDB_PRIMARY_IMAGE_URL);
GO

CREATE TABLE MOVIE(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IMAGE_ID NUMERIC NULL FOREIGN KEY REFERENCES IMAGE_MOVIE(ID),
	IMDB_ID VARCHAR(10) NOT NULL,
	IMDB_AGGREGATE_RATING DECIMAL NULL,
	IMDB_TITLE_TYPE_ID VARCHAR(50) NULL,
	IMDB_TITLE_TEXT VARCHAR(200) NOT NULL,
	RELEASE_YEAR INT NULL,
	RELEASE_DATE SMALLDATETIME NULL
);
GO

CREATE UNIQUE INDEX MOVIE_IMDB_ID_IDX
ON MOVIE(IMDB_ID);
GO

CREATE INDEX MOVIE_IMDB_TITLE_TEXT_IDX
ON MOVIE(IMDB_TITLE_TEXT);
GO

CREATE TABLE GENRE_MOVIE(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MOVIE_ID NUMERIC NULL FOREIGN KEY REFERENCES MOVIE(ID),
	IMDB_GENRE_ID VARCHAR(50) NOT NULL
)

CREATE INDEX GENRE_MOVIE_IDX
ON GENRE_MOVIE(IMDB_GENRE_ID);
GO

CREATE TABLE PLOT_MOVIE(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MOVIE_ID NUMERIC NULL FOREIGN KEY REFERENCES MOVIE(ID),
	IMDB_PLAINTEXT VARCHAR(MAX) NOT NULL,
	IMDB_LANGUAGE_ID VARCHAR(5) NULL
)

CREATE INDEX PLOT_MOVIE_IDX
ON PLOT_MOVIE(IMDB_LANGUAGE_ID);
GO

CREATE TABLE PRINCIPAL_CAST_MOVIE(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MOVIE_ID NUMERIC NULL FOREIGN KEY REFERENCES MOVIE(ID),
	IMAGE_ID NUMERIC NULL FOREIGN KEY REFERENCES IMAGE_MOVIE(ID),
	IMDB_NAME_ID VARCHAR(10) NOT NULL,
	IMDB_NAME VARCHAR(100) NOT NULL
)

CREATE INDEX PRINCIPAL_CAST_MOVIE_IDX
ON PRINCIPAL_CAST_MOVIE(IMDB_NAME);
GO

CREATE TABLE PRINCIPAL_CAST_MOVIE_CHARACTER(
	ID NUMERIC NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PRINCIPAL_CAST_MOVIE_ID NUMERIC NULL FOREIGN KEY REFERENCES PRINCIPAL_CAST_MOVIE(ID),
	IMDB_CHARACTER_NAME VARCHAR(100) NOT NULL
)

CREATE INDEX PRINCIPAL_CAST_MOVIE_CHARACTERS_IDX
ON PRINCIPAL_CAST_MOVIE_CHARACTER(IMDB_CHARACTER_NAME);
GO