# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: HomeLaptop

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: front/mycinelist

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: front/mycinelist

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/front/mycinelist'
    contents: |
       build/**
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyCineListServiceConnection'
    appType: 'webApp'
    WebAppName: 'mycinelist'
    deployToSlotOrASE: true
    ResourceGroupName: 'BC_AmarildoVictor_RG'
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'