// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCineList.Data.Context;

#nullable disable

namespace MyCineList.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230521221225_fix001")]
    partial class fix001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GENRE_MOVIE", b =>
                {
                    b.Property<int>("GenresID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("GenresID", "MovieID");

                    b.HasIndex("MovieID");

                    b.ToTable("GENRE_MOVIE");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IMDBGenreID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IMDBGenreText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("IMDBGenreID")
                        .IsUnique();

                    b.ToTable("GENRE", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.ImageMovie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("ImdbPrimaryImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ImdbPrimaryImageUrl");

                    b.ToTable("IMAGE_MOVIE", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("IMDBAggregateRatting")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("IMDBID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IMDBTitleText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IMDBTitleTypeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IMDBTitleTypeText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ImageMovieID")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IMDBID")
                        .IsUnique();

                    b.HasIndex("IMDBTitleText");

                    b.HasIndex("ImageMovieID");

                    b.ToTable("MOVIE", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PlotMovie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IMDBLanguageID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IMDBPlainText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IMDBLanguageID");

                    b.HasIndex("MovieID")
                        .IsUnique();

                    b.ToTable("PLOT_MOVIE", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PrincipalCastMovie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IMDBName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IMDBNameID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int?>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IMDBName");

                    b.HasIndex("ImageID");

                    b.HasIndex("MovieID");

                    b.ToTable("PRINCIPAL_CAST_MOVIE", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PrincipalCastMovieCharacter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IMDBCharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrincipalCastMovieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IMDBCharacterName");

                    b.HasIndex("PrincipalCastMovieID");

                    b.ToTable("PRINCIPAL_CAST_MOVIE_CHARACTER", (string)null);
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.ReleaseDate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MovieID")
                        .IsUnique();

                    b.ToTable("RELEASE_DATE", (string)null);
                });

            modelBuilder.Entity("GENRE_MOVIE", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCineList.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.Movie", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.ImageMovie", "ImageMovie")
                        .WithMany()
                        .HasForeignKey("ImageMovieID");

                    b.Navigation("ImageMovie");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PlotMovie", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.Movie", "Movie")
                        .WithOne("Plot")
                        .HasForeignKey("MyCineList.Domain.Entities.PlotMovie", "MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PrincipalCastMovie", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.ImageMovie", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID");

                    b.HasOne("MyCineList.Domain.Entities.Movie", "Movie")
                        .WithMany("PrincipalCastMovies")
                        .HasForeignKey("MovieID");

                    b.Navigation("Image");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PrincipalCastMovieCharacter", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.PrincipalCastMovie", "PrincipalCastMovie")
                        .WithMany("PrincipalCastMovieCharacters")
                        .HasForeignKey("PrincipalCastMovieID");

                    b.Navigation("PrincipalCastMovie");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.ReleaseDate", b =>
                {
                    b.HasOne("MyCineList.Domain.Entities.Movie", "Movie")
                        .WithOne("ReleaseDate")
                        .HasForeignKey("MyCineList.Domain.Entities.ReleaseDate", "MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Plot");

                    b.Navigation("PrincipalCastMovies");

                    b.Navigation("ReleaseDate");
                });

            modelBuilder.Entity("MyCineList.Domain.Entities.PrincipalCastMovie", b =>
                {
                    b.Navigation("PrincipalCastMovieCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
